version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wessberg/rollup-plugin-ts"
    versions:
    - 1.3.10
    - 1.3.11
    - 1.3.8
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
    - 3.9.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: rollup
    versions:
    - 1.32.1
